
//  LOG IN
POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username" : "tuan",
    "password" : "tuan123"
}


###
//  LOG OUT
POST  http://127.0.0.1:8000/api/logout
Content-Type: application/json

{

}

###
//  Register
POST  http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "username" : "quan",
    "nickname" : "quan123",
    "password" : "123"
}

###
//  Store restaurant
POST  http://127.0.0.1:8000/api/restaurant/store
Content-Type: application/json

{
    "name" : "Bruh Restaurant",
    "description" : "So bruh bruh lmao..",
}

###
//  Show restaurant
GET  http://127.0.0.1:8000/api/restaurant/index
Content-Type: application/json

{
    
}

###
//  Edit restaurant
GET  http://127.0.0.1:8000/api/restaurant/edit/1
Content-Type: application/json

{

}

###
//  Update restaurant
POST  http://127.0.0.1:8000/api/restaurant/update/1
Content-Type: application/json

{
    "name" : "TuanLe's Restaurant",
    "description" : "Top 1 server Earth",

}

###
//  Delete restaurant
DELETE   http://127.0.0.1:8000/api/restaurant/delete/14/x3sjjo1ZBBNfu9ldrFGiJiwPCIFNTeZqNBoXjWvVoiTdM9R7HAN6ouV5pWht4wWl0TP7DLFoGDKE66Jo2peOAXKh8OtMlKCZ7knMUi3ueaf4b9dr7lIi7IOXItpjVEkGL3PqHDZvcnaa6Is0mScZaoHa6q1yXTaZ7fiXu5v7RSxFjsl8UnpdaM7gWV40fuwHYtOvNyJda5Ikc9FGPPuHRZvgVUOyAOsptnoEw7YxJFLNXd6uOgwHc0ZVlCD8JjE5
Content-Type: application/json

{

}