
//  LOG IN
POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username" : "easty1p",
    "password" : "wM31s6zK"
}


//  LOG OUT
###
POST  http://127.0.0.1:8000/api/logout
Content-Type: application/json

{

}

###